# You are given house data dataset

In [1]:
import pandas as pd

df_house = pd.DataFrame({
    "size": [50, 60, 75, 80, 100, 120, 150, 200, 220, 250],
    "bedrooms": [1, 2, 2, 3, 3, 3, 4, 4, 5, 5],
    "price": [150000, 180000, 200000, 220000, 280000, 320000, 400000, 500000, 550000, 600000]
})

df_house

   size  bedrooms   price
0    50         1  150000
1    60         2  180000
2    75         2  200000
3    80         3  220000
4   100         3  280000
5   120         3  320000
6   150         4  400000
7   200         4  500000
8   220         5  550000
9   250         5  600000

In [2]:
df_house.head()

   size  bedrooms   price
0    50         1  150000
1    60         2  180000
2    75         2  200000
3    80         3  220000
4   100         3  280000

#Task 1

* Build Linear Regression model

* Compute RMSE and R²

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [4]:
X=df_house[['size','bedrooms']]
y=df_house['price']

In [5]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)

In [6]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [7]:
y_pred=model.predict(X_test)

In [8]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)
print(rmse,r2)

2400.7820831769095 0.9998315922684907

#Task 2

* Add polynomial features

* Compare results

In [9]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

In [10]:
polymodel=make_pipeline(PolynomialFeatures(degree=2),LinearRegression())

In [11]:
polymodel.fit(X_train,y_train)
poly_pred=polymodel.predict(X_test)

In [12]:
poly_rmse = np.sqrt(mean_squared_error(y_test, poly_pred))
poly_r2 = r2_score(y_test, poly_pred)

print("Polynomial RMSE:", poly_rmse)
print("Polynomial R2:", poly_r2)
print("Linear RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Linear R2:", r2)

Polynomial RMSE: 13399.020059476845
Polynomial R2: 0.9947543100495467
Linear RMSE: 2400.7820831769095
Linear R2: 0.9998315922684907

# Task 3

* Apply Ridge & Lasso

* Compare coefficients

In [13]:
from sklearn.linear_model import Ridge,Lasso

In [14]:
ridge=Ridge(alpha=10)
ridge.fit(X_train,y_train)

Ridge(alpha=10)

In [15]:
lasso=Lasso(alpha=1)
lasso.fit(X_train,y_train)

Lasso(alpha=1)

In [16]:
linear=LinearRegression()
linear.fit(X_train,y_train)
linear_pred=linear.predict(X_test)

In [17]:
linear_pred = linear.predict(X_test)
ridge_pred = ridge.predict(X_test)
lasso_pred = lasso.predict(X_test)

In [18]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)

In [19]:
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

print("Linear RMSE:", rmse(y_test, linear_pred))
print("Ridge RMSE:", rmse(y_test, ridge_pred))
print("Lasso RMSE:", rmse(y_test, lasso_pred))

Linear RMSE: 2400.7820831769095
Ridge RMSE: 4456.931823955371
Lasso RMSE: 2401.8041480123784

In [20]:
print("Linear coefficients:", linear.coef_)
print("Ridge coefficients:", ridge.coef_)
print("Lasso coefficients:", lasso.coef_)

Linear coefficients: [ 2105.55994136 10553.73858126]
Ridge coefficients: [2255.65633834 1565.88933985]
Lasso coefficients: [ 2105.64064913 10548.94436862]

# Task 4

* Use cross-validation

* Report average RMSE

In [21]:
from sklearn.model_selection import cross_val_score

In [22]:
scores=cross_val_score(LinearRegression(),X,y,cv=5,scoring='neg_mean_squared_error')
scores

array([-6.90128455e+07, -3.44088826e+08, -5.18193461e+07, -1.21509736e+08,
       -3.14296541e+08])

In [23]:
rmse_scores = np.sqrt(-scores)
avg_rmse = rmse_scores.mean()

print("Average RMSE:", avg_rmse)

Average RMSE: 12561.430014443693

# Task 5 (Reflection)

* Write 8–10 lines explaining:

* When regularization is necessary

* Why cross-validation is better than one split

* How to detect overfitting

In [23]:
# regularization is useful when a model is too complex and starts overfitting.
# it helps improve the model's ability to generalize to new data.
# ridge (L2) reduces large coefficients without making them exactly zero.
# lasso (L1) can reduce some coefficients to zero.
# cross-validation helps us evaluate how well a model performs on different subsets of data.
# it gives us a more reliable evaluation than using only one train-test split.
# overfitting happens when a model learns the training data too closely.
# we can detect it by comparing the training and testing errors.
# if the training error is low but the testing error is high, the model might be overfitting.