# Exercise Scenario

You are given a dataset about students.

Goal:
* Predict whether a student will pass or fail.

In [1]:
#dataset creation


import pandas as pd

df_students = pd.DataFrame({
    "study_hours": [1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 6, 9],
    "attendance":  [50, 55, 60, 65, 70, 75, 80, 90, 45, 85, 95, 88],
    "final_score": [45, 48, 55, 60, 68, 72, 85, 92, 40, 78, 88, 95],
})

# Target variable
df_students["pass"] = [0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1]

df_students

    study_hours  attendance  final_score  pass
0             1          50           45     0
1             2          55           48     0
2             3          60           55     0
3             4          65           60     1
4             5          70           68     1
5             6          75           72     1
6             7          80           85     1
7             8          90           92     1
8             2          45           40     0
9             3          85           78     1
10            6          95           88     1
11            9          88           95     1

#What Does This Dataset Represent?

* This dataset represents a small group of students and their academic performance.

* Each row corresponds to one student.

* The goal is to predict whether a student will pass or fail based on their behavior and engagement.


# Columns Description
## study_hours

* Number of hours the student studies per day.
* Range in this dataset: 1 to 9 hours.
* Intuition: More study hours → higher chance of passing.

## attendance

* Percentage of class attendance.
* Range in this dataset: 45% to 95%.
* Intuition: Higher attendance → better understanding → higher chance of passing.

## final_score

* Final exam score (out of 100).
* This value directly reflects performance.
* Important: This feature determines whether the student passed.

## pass (Target Variable)

1 → Student passed

0 → Student failed

This is the variable we want to predict.

#1 — Define the Problem

* Is this regression or classification?

* What is the target?

* What metric should be used?

## Answer:

classification, since we want to predict whether the student passes or fails.

target: pass column

since this is a classification problem: accuracy, precision, recall, and F1-score

#2- Detect Leakage

You are given features:



1.   Study hours
2.   Attendance
3.   Final score



Which one is leakage?

In [2]:
df_students['final_score']

0     45
1     48
2     55
3     60
4     68
5     72
6     85
7     92
8     40
9     78
10    88
11    95
Name: final_score, dtype: int64

# 3 — Build Baseline Model

* Split data
* Train simple model
* Evaluate properly

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X=df_students[['study_hours', 'attendance']]
y=df_students['pass']

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [6]:
from sklearn.linear_model import LogisticRegression

In [7]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [8]:
y_pred=model.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score, classification_report

In [10]:
accuracy=accuracy_score(y_test,y_pred)
print('accuracy: ',accuracy)

accuracy:  1.0

In [11]:
print(classification_report(y_test, y_pred, zero_division=0))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

#4 — Reflection

Write 8–10 lines:

* What mistakes could happen?
* Why is baseline important?
* What metric matters most and why?

In [12]:
# 1. high risk of data leakage:
# using final_score would cause leakage because it directly determines the target
# also evaluating the model on the same data used for training
# a small dataset can lead to unreliable evaluation results
# 2. a baseline model provides a starting point for measuring performance,
# it helps us determine whether more complex models are necessary
# 3. accuracy is useful because it measures the proportion of correct predictions